import { app, BrowserWindow, ipcMain, Menu, screen, Tray } from 'electron';
import isDev from 'electron-is-dev';
import Store from 'electron-store';

import path from 'path';
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

let tray: Tray = undefined;
let win: BrowserWindow = undefined;
const store = new Store();

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

const getWindowPosition = () => {
  const windowBounds = win.getBounds();
  const trayBounds = tray.getBounds();

  let x = Math.round(trayBounds.x + trayBounds.width / 2 - windowBounds.width / 2);

  const screenWidth = screen.getPrimaryDisplay().workAreaSize.width;
  const screenHeight = screen.getPrimaryDisplay().workAreaSize.height;

  x = Math.max(3, Math.min(x, screenWidth - windowBounds.width - 3));

  let y;

  if (trayBounds.y > screenHeight / 2) {
    y = Math.round(trayBounds.y - windowBounds.height - 3);
  } else {
    y = Math.round(trayBounds.y + trayBounds.height + 3);
  }

  return { x: x, y: y };
};

const getIcon = (iconFileName: string): string => {
  const imgPath = `icons/${iconFileName}`;
  return isDev ? path.join(__dirname, `../../src/${imgPath}`) : path.join(__dirname, `./${imgPath}`);
};

const createWindow = (): void => {
  win = new BrowserWindow({
    width: 360,
    height: 112,
    show: false,
    frame: false,
    fullscreenable: false,
    resizable: false,
    transparent: true,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // preload: path.join(__dirname, 'renderer.js'),
      // nodeIntegrationInSubFrames: true,
      webviewTag: true,
      nodeIntegration: true,
      contextIsolation: false,
    },
    icon: getIcon('time-on.png'),
  });

  win.setAlwaysOnTop(true, 'normal');

  win.setMenuBarVisibility(false);

  win.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  win.webContents.openDevTools({
    mode: 'detach',
  });

  win.on('blur', () => {
    win.webContents.send('blur');
  });

  win.on('closed', () => {
    win = null;
  });
};

const showWindow = ({ withFocus = true }: { withFocus?: boolean } = {}) => {
  const position = getWindowPosition();
  win.setPosition(position.x, position.y, false);
  win.show();
  if (withFocus) {
    win.focus();
  }
};

const createTray = () => {
  tray = new Tray(getIcon('time-off.png'));
  tray.on('double-click', function () {
    showWindow();
  });

  const contextMenu = Menu.buildFromTemplate([{ label: 'Exit', type: 'normal', role: 'quit' }]);
  tray.setContextMenu(contextMenu);
};

app.on('ready', () => {
  try {
    createTray();
    createWindow();
  } catch (e) {
    console.log(e);
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

ipcMain.on('hideWindow', () => {
  win.hide();
});

ipcMain.on('showWindow', () => {
  showWindow({ withFocus: false });
});

ipcMain.handle('getStoreValue', (event, key) => {
  return store.get(key);
});
ipcMain.handle('setStoreValue', (event, { key, value }) => {
  return store.set(key, value);
});

ipcMain.on('startTimer', () => {
  tray.setImage(getIcon('time-on.png'));
});

ipcMain.on('stopTimer', () => {
  tray.setImage(getIcon('time-off.png'));
});

ipcMain.on('startChill', () => {
  tray.setImage(getIcon('time-idle.png'));
});
